### ISSUE TITLE
when trying test data get this error

### ISSUE THREAD

**Issue by AbraamSa** [renzilin/NanoForenSTR#2]
## The locus D1S1656 is under inference {1/1}:   0%|     | 0/1 [00:00<?, ?it/s]
/bin/sh: 1: None: not found
## The locus D1S1656 is under inference {1/1}:   0%|     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "../nanoforenstr.py", line 196, in <module>
    args.func(args)
  File "../nanoforenstr.py", line 141, in LA
    seq_prefix, seq_suffix = fetch_flanking_seq(chrom, start, end, flanking_len, reference_genome, samtools)
  File "../nanoforenstr.py", line 96, in fetch_flanking_seq
    pre_flanking = faidx_output.split('\n')[1]
IndexError: list index out of range

**Comment by renzilin** [comment]
Hi AbraamSa,
Sorry for the incomplete description, and I revised the readme file. 
In detail, the input contains 5 parts:
- the path of bam file;
- the str pattern (repeat motifs) file we provide;
- ID: a string for output name
- ref: reference genome with samtools index, we used hg19;
- the path of samtools; if you use conda to manage the computing environment, you can just use `samtools` as the parameter.

If you have any question, please let me know.

**Comment by renzilin** [comment]
> ## The locus D1S1656 is under inference {1/1}: 0%| | 0/1 [00:00<?, ?it/s]
> /bin/sh: 1: None: not found
> 
> ## The locus D1S1656 is under inference {1/1}: 0%| | 0/1 [00:00<?, ?it/s]
> Traceback (most recent call last):
> File "../nanoforenstr.py", line 196, in
> args.func(args)
> File "../nanoforenstr.py", line 141, in LA
> seq_prefix, seq_suffix = fetch_flanking_seq(chrom, start, end, flanking_len, reference_genome, samtools)
> File "../nanoforenstr.py", line 96, in fetch_flanking_seq
> pre_flanking = faidx_output.split('\n')[1]
> IndexError: list index out of range

Hi AbraamSa,
Sorry for the incomplete description, and I revised the readme file. 
In detail, the input contains 5 parts:
- the path of bam file;
- the str pattern (repeat motifs) file we provide;
- ID: a string for output name
- ref: reference genome with samtools index, we used hg19;
- the path of samtools; if you use conda to manage the computing environment, you can just use `samtools` as the parameter.

If you have any question, please let me know.

**Comment by AbraamSa** [comment]
thank u it is working now
